[package]
name = "instrumentality"
version = "0.1.0"
edition = "2021"

[dependencies]
# into_json hangs indefinitely on v0.5.0-rc1, fixed in master but no release since.
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "ae0ccf43f11be5c00bb9cd49996c8bb06a7e1651", features = ["tls", "json"] }
mongodb = "2.1.0"
toml = "0.5.8"
chrono = { version = "0.4.19", features = ["serde"] }
serde = "1.0.136"
serde_json = "1.0.78"
getrandom = "0.2.4"
uuid = "0.8.2"
tokio-stream = "0.1.8"

[dev-dependencies]
regex = "1.5.5"

[[bin]]
name = "instrumentality"

[lib]
name = "instrumentality"
path = "src/lib.rs"