[content_types]
PLATFORM_1 = ["post", "story", "live"]
PLATFORM_2 = ["scrobble"]

[presence_types]
PLATFORM_2 = ["listening_now"]
PLATFORM_3 = ["streaming"]

[mongodb]
hosts = "127.0.0.1"
port = "27017"
user = "instrumentality"
password = ""
database = "instrumentality"

[settings]
log_level = "INFO"

[network]
address = "127.0.0.1"
port = "8000"

[tls]
# Can be taken directly from Let's Encrypt.
cert = "tls/cert.pem"
key = "tls/privkey.pem"