[content_types]
instagram = ["post", "story", "live"]
twitter = ["tweet", "like", "retweet", "story"]
last_fm = ["scrobble"]
twitch_tv = ["stream_start", "video", "stream_end"]

[presence_types]
twitter = ["follower_count_increase"]
last_fm = ["now_playing"]
twitch_tv = ["live"]

[mongodb]
hosts = "127.0.0.1"
port = "27017"
user = "instrumentality"
password = ""
database = "instrumentality"

[settings]
log_level = "INFO"

[network]
address = "127.0.0.1"
port = "12321"

[tls]
cert = "tls/cert.pem"
key = "tls/privkey.pem"